name: MoonBit CI

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1
        with:
          version: 0.10.3

      - name: Show toolchain
        run: moon version --all

      - name: Format check
        run: moon fmt --check

      - name: Generate interface info
        run: moon info

      - name: Static check
        run: moon check --deny-warn

      - name: Test
        run: moon test
